// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC58csRcrVEgvClXTJfzIbgIcQIKGReX7o',
    appId: '1:667920084120:web:fbd49fdbf0cace299db4ed',
    messagingSenderId: '667920084120',
    projectId: 'chattapp-711b0',
    authDomain: 'chattapp-711b0.firebaseapp.com',
    storageBucket: 'chattapp-711b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-ehOQfiqMiIryK0uSzRJ6C4Fr6SeQYM',
    appId: '1:667920084120:android:058c2f84a7a574ab9db4ed',
    messagingSenderId: '667920084120',
    projectId: 'chattapp-711b0',
    storageBucket: 'chattapp-711b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtY5U77BFIVf1R_PKirxu1Fu7lzR-cZzE',
    appId: '1:667920084120:ios:04ac7dea554204079db4ed',
    messagingSenderId: '667920084120',
    projectId: 'chattapp-711b0',
    storageBucket: 'chattapp-711b0.firebasestorage.app',
    iosBundleId: 'com.example.myChattApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtY5U77BFIVf1R_PKirxu1Fu7lzR-cZzE',
    appId: '1:667920084120:ios:04ac7dea554204079db4ed',
    messagingSenderId: '667920084120',
    projectId: 'chattapp-711b0',
    storageBucket: 'chattapp-711b0.firebasestorage.app',
    iosBundleId: 'com.example.myChattApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC58csRcrVEgvClXTJfzIbgIcQIKGReX7o',
    appId: '1:667920084120:web:262e91e1efb1cd939db4ed',
    messagingSenderId: '667920084120',
    projectId: 'chattapp-711b0',
    authDomain: 'chattapp-711b0.firebaseapp.com',
    storageBucket: 'chattapp-711b0.firebasestorage.app',
  );

}